### ISSUE TITLE
Make edit & remove song

### ISSUE THREAD

**Issue by delipnugraha** [41studio/discjoke#2]
If I want to change list song I want edit my playlist and can remove too, please follow up this feature :dart: I can't wait this feature to build  :+1:

**Comment by aditiamahdar** [comment]
Actually edit functionality only available for DJ, but I think we can add edit or remove for each person who responsible for their videos

**Comment by agungyuliaji** [comment]
How if we add remove feature for admin/moderator (if any that role), inappropriate content from users must be considered.

**Comment by aditiamahdar** [comment]
here we call admin as DJ, the one who play music and he has ability to remove a music
