### ISSUE TITLE
I need banned feature

### ISSUE THREAD

**Issue by ririsrismawati** [41studio/discjoke#3]
I need banned feature for song that we hated/ contains SARA. When we down voted the song, it will automatically skip the song.

**Comment by mada41** [comment]
i think will better if there is configuration for each channel, to set the auto banned.
cc @dimasjt @aditiamahdar

**Comment by aditiamahdar** [comment]
Thanks for the suggestion, we will do our best!

**Comment by luaysuarna** [comment]
@aditiamahdar @dimasjt, I have mockup for player application, glad if somebody can implement to this application :)

https://www.behance.net/gallery/34816601/Web-UX-for-Music-Player-Music-Box

**Comment by mada41** [comment]
please open new ticket @luaysuarna for different purpose :grin:

**Comment by ririsrismawati** [comment]
Why you closed the issue @dimasjt ? have you been fixed it? Please tell me..

**Comment by aditiamahdar** [comment]
@ririsrismawati we have created ban feature, but it only available for DJ maybe you can confirm this feature to nearest DJ

**Comment by ririsrismawati** [comment]
Ah glad to hear that! Thankyou for the explanation @aditiamahdar. I'm sorry, I don't know before. Maybe next time explain first before close the issue :)

**Comment by mada41** [comment]
i think will better if you have reference the commit message to issue page if any @dimasjt , hint -> https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by aditiamahdar** [comment]
ah yes sorry we forgot to reference the commit to this issue, will do it later thanks guys!

**Comment by agungyuliaji** [comment]
mantap bang
