### ISSUE TITLE
auto delete list

### ISSUE THREAD

**Issue by ekihartari** [41studio/discjoke#7]
I think we need to auto delete list at 00:00 every day

**Comment by mada41** [comment]
+1 , we can put this is option for each channel

**Comment by aditiamahdar** [comment]
hmmm not sure this is best option, since sometime DJ want to save time with no need to re-input the videos.
Actually later we are planning to add feature like _shuffle videos_ and _drag n drop_ so DJ can shuffle the playlist or drag n drop to re-arrange the order
what do you think @ekihartari ?

**Comment by ekihartari** [comment]
sometimes we want to listen another song and don't want to listen same songs again.. hmm, maybe we can add function to "delete all" list if DJ want to delete all in the morning..

and you know, when DJ deleting a song when we were still play a song, it will automatically refresh and change the song to the next song.. @aditiamahdar

**Comment by aditiamahdar** [comment]
aaah that's better solution, we will add "Delete All" button to clear the playlist

@ekihartari regarding bug on playing next video when DJ remove a video it's fixed already
