### ISSUE TITLE
Youtube Short URL is not valid

### ISSUE THREAD

**Issue by andreasarnol02** [41studio/discjoke#9]
Youtube provide us their Short URL for example https://youtu.be/ocTdA8NytIc
I can't add it to discjoke
It' says "Invalid URL" eventhough it's from youtube

**Comment by aditiamahdar** [comment]
Hi @andreasarnold02 

Thanks for the report, currently we have not handle youtube short url, but I think we will consider that so user will be able to add through short url of youtube

Best Regards,
Aditia
